### ISSUE TITLE
Cannot set static IP

### ISSUE THREAD

**Issue by JPluess** [armbian/config#109]
I have successfully connected to my wife, but setting a static IP fails. 
![grafik](https://user-images.githubusercontent.com/7995240/88386983-d7b39f00-cdb1-11ea-9c31-9fdeca119535.png)

I tried to save like so:
![grafik](https://user-images.githubusercontent.com/7995240/88387089-0af62e00-cdb2-11ea-8fa0-6850d9f24e5e.png)

Why does it say adapter lo above?  Isn’t it wlan0? Like so:
![grafik](https://user-images.githubusercontent.com/7995240/88387207-4ee93300-cdb2-11ea-8ec2-1dd27851ba1d.png)

I use an OrangePI Lite2 H6

thanks, ;)

**Comment by igorpecovnik** [comment]
> I have successfully connected

Thanks for reporting an issue. We will look into it when possible.

> Why does it say adapter lo above? Isn’t it wlan0? Like so:

Perhaps you used some other tool to connect or its simply a bug that doesn't count that? Support terms in general https://github.com/armbian/build#support

**Comment by EvilOlaf** [comment]
Tried the same with OrangePi Zero. It automatically selects eth0 for me when selecting "static". So maybe there is an issue with interface selection?

**Comment by JPluess** [comment]
I re-burned this image:  Armbian_20.05.2_Orangepilite2_buster_current_5.4.43.img with Rufus

Right after booting and setting up my account, I only used armbian-config tool to make my settings


1. changed time zone, Zurich
2. change locales de_CH.UTF-8 and set as default
3. changed keyboard to CH
4. changed mirror to Denmark
5. connected to my WIFI

  **6a. Failed to change IP settings.
6b. After reboot issue persists.**

7. I did an update / upgrade command:
![grafik](https://user-images.githubusercontent.com/7995240/88398222-5f56d900-cdc5-11ea-9b9f-f2985384438c.png)

8. after a reboot I tried again to set IP, with no success
![grafik](https://user-images.githubusercontent.com/7995240/88398470-b9579e80-cdc5-11ea-8047-700a45d36852.png)

**Comment by igorpecovnik** [comment]
> Failed to change IP settings.

Yes, we register it as a bug.

**Comment by igorpecovnik** [comment]
armbian-config is a wrapper for other low level apps .... try using:

      nmtui-edit

for setting fixed IP.

**Comment by lrhorer** [comment]
Confirmed this does not work on the latest version of Buster.  /etc/network/interfaces is ignored.  The only way I was able to set a static IP on either WiFi or Ethernet was to remove network-manager and its libraries, install dhcpcd5 and edit /etc/ /etc/dhcpcd.conf.  For wireless, I also had to create /etc/wpa_supplicant/wpa_supplicant.conf.

**Comment by igorpecovnik** [comment]
New mechanism has been implemented into https://github.com/armbian/configng
