### ISSUE TITLE
Insecure temp file handling

### ISSUE THREAD

**Issue by ThomasKaiser** [armbian/config#11]
Since `armbian-config` is now part of every new Armbian install and will be promoted more and more we have to take care about potential security issues.

Insecure handling of files below `/tmp/` being the most severe issue based on a quick look.

Can you please take care of these issue (using `mktemp [-d]` where possible)?

**Comment by ThomasKaiser** [comment]
Related: https://github.com/armbian/config/commit/c216935acf19bbbf717fee4ee94b0f0322afab2c

**Comment by igorpecovnik** [comment]
https://github.com/armbian/configng
