### ISSUE TITLE
I2C Clock Speed

### ISSUE THREAD

**Issue by nogleo** [armbian/config#111]
Noob here!

I need to change the Clock Speed from the I2C bus on my OrangePi running Armbian. I've seen in the datasheet the board is able to use FastMode (400 kHz). How Am I suposed to do that?

Thanks a lot in advance

**Comment by martinayotte** [comment]
See the following post on the forum (search would have reveal it) :+1: 
https://forum.armbian.com/topic/3030-h3-i2c-speed/?do=findComment&comment=21132

**Comment by nogleo** [comment]
I saw the post previously and by my understanding it would take building the OS to make this change, correct? Forgive me if I'm wrong.

I just wanted to know if there is, like in the RPi for example, a way to change it after built like the config. txt or a change in parameter in a file

**Comment by igorpecovnik** [comment]
This problem is not related to armbian-config.

**Comment by martinayotte** [comment]
As the post explained, with Mainline kernel, you only need to edit DT, no need to rebuild kernel.

**Comment by nogleo** [comment]
Sorry but I don't even know what DT stands for... total noob here

**Comment by EvilOlaf** [comment]
> 
> 
> Sorry but I don't even know what DT stands for... total noob here

`Device Tree` and please refer to the Armbian forums to further discussion. As mentioned earlier this issue tracker is for the armbian-config tool only.

**Comment by igorpecovnik** [comment]
>  total noob here

https://linuxjourney.com/
https://github.com/armbian/build#support

**Comment by spyderdyne** [comment]
> See the following post on the forum (search would have reveal it) 👍 https://forum.armbian.com/topic/3030-h3-i2c-speed/?do=findComment&comment=21132

Search revealed this issue thread. This is why everyone should be on board with just providing answers if they are going to post en lieu of snarky criticisms or posting links for further research. FWIW
