### ISSUE TITLE
/etc/apt/apt.conf.d/50unattended-upgrades deleted on every update

### ISSUE THREAD

**Issue by h1618** [armbian/config#117]
Everytime armbian-config is updated, my 50unattended-upgrades in /etc/apt/apt.conf.d/ is deleted. Took some time until I found the offender, but the some last updates shows it. How come? This behavior is rather rude ...

**Comment by igorpecovnik** [comment]
Not a part of armbian-config but "board support packag"
https://github.com/armbian/build/blob/master/lib/makeboarddeb.sh#L42

It has been on the list to change the behavior for months and it will stay there unless someone pick it up.

**Comment by h1618** [comment]
Ok, seems this is called by install scripts of armbian-config ...
