### ISSUE TITLE
Error install dphys-swapfile

### ISSUE THREAD

**Issue by np105** [armbian/config#119]
In my lime2 not correct install dphys-swapfile:
Настраивается пакет dphys-swapfile (20100506-5) …
Job for dphys-swapfile.service failed because the control process exited with error code.
See "systemctl status dphys-swapfile.service" and "journalctl -xe" for details.
invoke-rc.d: initscript dphys-swapfile, action "start" failed.
● dphys-swapfile.service - dphys-swapfile - set up, mount/unmount, and delete a swap file
   Loaded: loaded (�]8;;file://lime2/lib/systemd/system/dphys-swapfile.service/lib/systemd/system/dphys-swapfile.service�]8;;; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-11-15 01:03:06 MSK; 107ms ago
     Docs: �]8;;man:dphys-swapfile(8)man:dphys-swapfile(8)�]8;;
  Process: 31216 ExecStart=/sbin/dphys-swapfile setup (code=exited, status=0/SUCCESS)
  Process: 31248 ExecStart=/sbin/dphys-swapfile swapon (code=exited, status=255/EXCEPTION)
 Main PID: 31248 (code=exited, status=255/EXCEPTION)

ноя 15 01:03:05 lime2 systemd[1]: Starting dphys-swapfile - set up, mount/unmount, and delete a swap file...
ноя 15 01:03:06 lime2 dphys-swapfile[31216]: computing size, want /var/swap=1998MByte, generating swapfile ... of 1998MBytes
ноя 15 01:03:06 lime2 dphys-swapfile[31248]: swapon: /var/swap: swapon failed: Недопустимый аргумент
ноя 15 01:03:06 lime2 systemd[1]: dphys-swapfile.service: Main process exited, code=exited, status=255/EXCEPTION
ноя 15 01:03:06 lime2 systemd[1]: dphys-swapfile.service: Failed with result 'exit-code'.
ноя 15 01:03:06 lime2 systemd[1]: Failed to start dphys-swapfile - set up, mount/unmount, and delete a swap file.
dpkg: ошибка при обработке пакета dphys-swapfile (--configure):
 installed dphys-swapfile package post-installation script subprocess returned error exit status 1

To work:
/etc/dphys-swapfile:
CONF_SWAPFILE=/var/swap
CONF_SWAPSIZE=2048

# dphys-swapfile setup
# dd if=/dev/zero of=/var/swap bs=2MiB count=1024
# mkswap /var/swap
# dphys-swapfile setup
must not "create", must use

# apt -f install

**Comment by igorpecovnik** [comment]
This is not config issue - please use forums https://forum.armbian.com/forum/25-common-issues-peer-to-peer-technical-support/
