### ISSUE TITLE
Armbian mirror selection

### ISSUE THREAD

**Issue by lanefu** [armbian/config#120]
Add support to configure armbian mirror via query to https://apt.armbian.com/mirrors

Should be able to take its JQ output and make an easy to work with list to update /etc/apt/sources.list.d/armbian.list

more info here

https://docs.armbian.com/User-Guide_Fine-Tuning/#choosing-an-apt-mirror

**Comment by igorpecovnik** [comment]
We want users to ask to select a region and / or specific mirror?

**Comment by lanefu** [comment]
> We want users to ask to select a region and / or specific mirror?

If they can have the choice of either that would br best.
