### ISSUE TITLE
ArmbianConfig -> Personal -> Welcome does not open

### ISSUE THREAD

**Issue by ChrTall** [armbian/config#160]
I would like to enable the welcome screen for the armbian-buster odroidn2 image.
But when I try to open "Welcome" under "Personal" in the "Armbian-Config" the image disappears for a split second with an error message, that I can not read and then the "Personal" settings page is open again.
I think I haven't disabled the  welcome screen and would like to re-enable it. Is there a log file somewhere which I can inspect to resolve the error message that I can not read?

`sudo lsb_release -a
`
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

`sudo uname -a`
Linux odroidn2 5.10.81-meson64 #21.08.6 SMP PREEMPT Mon Nov 22 11:21:51 UTC 2021 aarch64 GNU/Linux

**Comment by igorpecovnik** [comment]
Moved to https://github.com/armbian/configng/pull/89
