### ISSUE TITLE
Installing tvheadend doesn't work on Ubuntu-based Armbian systems

### ISSUE THREAD

**Issue by hello-world-dot-c** [armbian/config#162]
As reported in https://forum.armbian.com/topic/20523-armbian-config-installation-of-tvheadend-doesnt-work/.

In
https://github.com/armbian/config/blob/c9a9b494c3069807471bb00c0336566cd186f6d9/debian-software#L615-L635

the command line to add the tvheadend repository is wrong. Instead of

`add-apt-repository -y add-apt-repository ppa:mamarley/tvheadend-git >/dev/null 2>&1`

it should be

`add-apt-repository -y ppa:mamarley/tvheadend-git >/dev/null 2>&1`

**Comment by EvilOlaf** [comment]
fixed 10 hours ago
https://github.com/armbian/config/commit/e6f2038e0bd788e9df9ead56ab6817a505f7cd00
