### ISSUE TITLE
no boot, after rpi-7inch-lcd enabled

### ISSUE THREAD

**Issue by 0xD8C4A475** [armbian/config#164]
no boot, after rpi-7inch-lcd enabled

Hardware: Rockpi4-b-plus
OS:   Armbian 21.02.1 Buster with Linux 4.4.213-rockchip64

No boot, no image on lcd or hdmi, does nothing.

![rpi4bp](https://user-images.githubusercontent.com/3819192/176854629-2818c639-3af8-4bd0-b809-26b45783b6bf.png)

**Comment by igorpecovnik** [comment]
> No boot, no image on lcd or hdmi, does nothing.

armbian-config does the job right. It enables overlay, the rest goes this way https://www.armbian.com/bugs/
