### ISSUE TITLE
Hotspot visible on Orange pi pc plus until check_advanced_modes

### ISSUE THREAD

**Issue by Jodaille** [armbian/config#169]
Hello,

using Armbian_22.05.4_Orangepipcplus_jammy_current_5.15.48 image on an Orange Pi pc plus :)

I can see "ARMBIAN" hotspot during configuration, and notice that it disappears at the step check_vht_capab()

I have cloned the repository, and I have commented few lines about check_advanced_modes parts and the hotspot can be seen and is working.

I am not sure to be able to understand how the script works, 
but I will give a try to find a better solution than commenting a whole part of the file.

attached a git diff output of debian-config-jobs file
[debian-config-jobs.diff.txt](https://github.com/armbian/config/files/9332893/debian-config-jobs.diff.txt)

Have a nice day

**Comment by igorpecovnik** [comment]
Try new mechanism https://github.com/armbian/configng
