### ISSUE TITLE
Wifi connection configured wrongly if device has to be connected to Wifi AP configured with  WPA2 + WPA3

### ISSUE THREAD

**Issue by volkmarnissen** [armbian/config#177]
According to this document
https://wiki.archlinux.org/title/wpa_supplicant#Connections_to_pure_WPA3-SAE_access_points
chapter 6.6 and 6.7 armbian-config  needs to  configure  wpasupplicant.conf differently than in 22.04 bullseye.

For pure WPA3 
ssid="network SSID"
key_mgmt=SAE
sae_password="the.literal.wifi.password"
ieee80211w=2

For mixed WPA2/WPA3
ssid="network SSID"
key_mgmt=WPA-PSK-SHA256
psk=xxx
ieee80211w=2

However in mixed mode, my device worked also using the WPA3 (SAE) settings.
This depends on the Wifi adapter. If it supports SAE, it will work.

If the AP is configured for WPA2 only it will also work properly.

The current configuration makes it impossible to configure Wifi if the router is in WPA2/WPA3 mode.

**Comment by igorpecovnik** [comment]
Please try new mechanism https://github.com/armbian/configng
