### ISSUE TITLE
DTB package not reinstalled on kernel switch

### ISSUE THREAD

**Issue by seth-hunter** [armbian/config#179]
Commit 9c793ad4c863af4b919ca4cf7f0afe5e777eb03f placed dtb installation behind an erroneous apt-search.  apt does not support searching by version, therefore this check always fails and dtb package gets removed but not reinstalled. This is causing devices running 2022.11 that switch kernel versions to fail to boot.

**Comment by seth-hunter** [comment]
Tagging @igorpecovnik - this may be considered urgent as it is bricking 2022.11 systems that attempt to switch kernels via armbian-config.

**Comment by igorpecovnik** [comment]
ok, will be pushed out asap, takes up to 48h to sync with all servers ... (also we are working to get this time down to <1h by smart repository enablement)

**Comment by igorpecovnik** [comment]
synching ... not in index yet.
https://fi.mirror.armbian.de/apt/pool/main/a/armbian-config/
