### ISSUE TITLE
gpg: can't create '/etc/apt/keyrings/docker.gpg': No such file or directory at fresh armbian install

### ISSUE THREAD

**Issue by yswtrue** [armbian/config#181]
When I install docker by armbian-config get these error:
```
gpg: can't create '/etc/apt/keyrings/docker.gpg': No such file or directory
gpg: no valid OpenPGP data found.
gpg: dearmoring failed: No such file or directory
(23) Failed writing body
```
And I create folder `/etc/apt/keyrings` and re-run again it works again.

**Comment by iav** [comment]
What OS based your armbian image? Ubuntu/Debian, and version number?

**Comment by yswtrue** [comment]
Armbian: 22.​11.​1 ​bullseye current
board: rockpi 4c+
I use this image: Armbian_​22.​11.​1_​Rockpi-​4cplus_​bullseye_​current_​5.​15.​80.​img.​xz

**Comment by iav** [comment]
ok, thank you.
Do you need a workaround or have docker working already?

**Comment by yswtrue** [comment]
Docker is working now.
