### ISSUE TITLE
Jammy - avahi install missing dependency - libnss-mdns

### ISSUE THREAD

**Issue by sfx2000** [armbian/config#189]
Avahi needs libnss-mdns to successfully do lookups on the local network.

Tested on Jammy

Armbian_23.02.1_Nanopineo2_jammy_current_5.15.93.img.xz

Not sure if other targets are affected - recall that this target defaults to CLI only

=============

sfx@nano2:~$ ping raspy2.local
ping: raspy2.local: Name or service not known
sfx@nano2:~$ sudo apt install libnss-mdns -y && sudo service avahi-daemon restart
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Suggested packages:
  avahi-autoipd | zeroconf
The following NEW packages will be installed:
  libnss-mdns
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 26.6 kB of archives.
After this operation, 127 kB of additional disk space will be used.
Get:1 http://ports.ubuntu.com jammy/main arm64 libnss-mdns arm64 0.15.1-1ubuntu1 [26.6 kB]
Fetched 26.6 kB in 1s (50.2 kB/s)      
Selecting previously unselected package libnss-mdns:arm64.
(Reading database ... 40954 files and directories currently installed.)
Preparing to unpack .../libnss-mdns_0.15.1-1ubuntu1_arm64.deb ...
Unpacking libnss-mdns:arm64 (0.15.1-1ubuntu1) ...
Setting up libnss-mdns:arm64 (0.15.1-1ubuntu1) ...
First installation detected...
Checking NSS setup...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
sfx@nano2:~$ ping raspy2.local
PING raspy2.local (192.168.1.140) 56(84) bytes of data.
64 bytes from raspy2.lan (192.168.1.140): icmp_seq=1 ttl=64 time=1.56 ms
64 bytes from raspy2.lan (192.168.1.140): icmp_seq=2 ttl=64 time=10.4 ms
^C
--- raspy2.local ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 1.559/6.004/10.449/4.445 ms

**Comment by EvilOlaf** [comment]
Please test by chance.
