### ISSUE TITLE
script of ispconfig3_install does‘t work 

### ISSUE THREAD

**Issue by chocoalwayslate** [armbian/config#195]
script of ispconfig3_install does‘t work
when luncher the install script , stoped at getmail4 ,It appears that the getmail4 version has been abandoned for update use and cannot capture the update source. So the installation cannot continue.

**Comment by igorpecovnik** [comment]
Yes, we are aware. It is beyond our possibility to maintain such a complex install. We won't provide this in https://github.com/armbian/configng anymore.
