### ISSUE TITLE
hdmi problems

### ISSUE THREAD

**Issue by ahasfasd** [armbian/config#199]
Hi, I came across a problem. I used this as an embeded os for TV. But when I flashed the system into the memory, the hdmi interface didn't have any signal. My cpu is amlogic s905I3/3b.
Thanks in advance, looking forward to your reply.

**Comment by igorpecovnik** [comment]
Support for tv boxes https://forum.armbian.com/forum/24-tv-boxes/

**Comment by ahasfasd** [comment]
OK, thanks.
