### ISSUE TITLE
armbian-config -> install kernel headers fails

### ISSUE THREAD

**Issue by Aljumaili85** [armbian/config#20]
Hi ,
armbian-config is not able to download kernel headers . I am using armbian for Allwinner A20 (Armbian ubuntu - legecy kernel 3.4.113-sun7i ) . any suggestion or even manual installation from terminal  ??

**Comment by igorpecovnik** [comment]
Try using development branch of armbian-config which is accessible from the beta repository or check this page for manual installation: https://www.armbian.com/kernel/

**Comment by Aljumaili85** [comment]
Thanks Igor, I manged to download it manually but  when I do make scripts nothing show as you explained on the bellowing post 
![untitled](https://user-images.githubusercontent.com/22834680/39671626-fff44cae-511b-11e8-9708-0980a46dcc2c.jpg)

**Comment by igorpecovnik** [comment]
Strange. Then open a support topic here: https://forum.armbian.com/forum/7-allwinner-a20/ Please provide all possible data most important: armbianmonitor -u
