### ISSUE TITLE
switch nighly to stable not working [?]

### ISSUE THREAD

**Issue by rkozlo** [armbian/config#202]
Being testing nigtly and now i want to switch to stable but it seems to not working at all. Doing
`/usr/sbin/armbian-config main=System selection=Stable`
as help shows, downloading some packages and it doing some stuffs, vut ends with nothing. Still 
```
Welcome to Armbian 23.02.2 Bullseye with Linux 6.1.11-meson64

No end-user support: untested automated build
```
as motd. Is there a way to switch back to stable release?

**Comment by igorpecovnik** [comment]
Please try new mechanism https://github.com/armbian/configng
