### ISSUE TITLE
Rock-5C rk3588s2 top USB3 port not working

### ISSUE THREAD

**Issue by CT1IQI** [armbian/config#218]
Edge kernel with DT based dts for the rock-5c board used.
Both USB2 ports work fine, and also the bottom USB3 port.
But the top USB3 one is not activated in normal usage mode.
When writing the OS image to eMMC that same port, with the board per jumper set to mask rom mode, is working fine, using rkdeveloptool. After reboot with the mask rom jumper removed the OS boots fine but that USB port becomes inactive.

**Comment by EvilOlaf** [comment]
This hasn't anything to do with armbian-config utility.
https://armbian.com/bugs
