### ISSUE TITLE
Error when set static IP

### ISSUE THREAD

**Issue by joaobosconff** [armbian/config#223]
shows this message:

/usr/lib/armbian-config/functions-network.sh: line 229: route: command not found

Using armbian 24.5.5 stable

kernel: 6.1.75-vendor-rk35xx

device : orange pi 5

image: Armbian_24.5.5_Orangepi5_bookworm_vendor_6.1.75_minimal.img.xz

**Comment by EvilOlaf** [comment]
until fixed: https://docs.armbian.com/User-Guide_Networking/
