### ISSUE TITLE
Armbian GUI password 

### ISSUE THREAD

**Issue by testocpp** [armbian/config#227]

**Comment by testocpp** [comment]
Hi 

New to the enviroment so may be missing something obvious on my side but even after mutiple attempts I am not able to log into Armbian GUI (for the following built) for bananapi M5. GUI shows "pi" username instead of root on the green gui screen and not been able to find password for the "pi" username. Tried the usual 1234, armbian,etc password none of which worked. 

Armbian_24.8.1_Bananapim5_bookworm_current_6.6.47_xfce_desktop.img.xz

SSH seems to be disabled therefore not able to use that route and cannot change to another user (such as root) to login. 

Looking for help on how to resolve this. 

Regards

**Comment by igorpecovnik** [comment]
> Looking for help on how to resolve this.

https://forum.armbian.com/
