### ISSUE TITLE
nothing in software->hardware->i2c

### ISSUE THREAD

**Issue by ybelievehaha1** [armbian/config#228]
Hello
   I have connect one led which is ssd1306, and when i build the kernel, i have choose i2c to support ssd1306, but when use this system, i can not find device file in /dev/i2c-xx，should any one can help me

**Comment by EvilOlaf** [comment]
Check with forums. I doubt anyone will read this here for once armbian-config is going to be deprecated and for the other this "bug report" lacking fundamental information like board, branch....
`armbianmonitor -u`
