### ISSUE TITLE
Fix openhab 4 install

### ISSUE THREAD

**Issue by moodyblue** [armbian/config#229]
Openhab 4 uses java zulu17, but the installer still mentions zulu11

openhab-addon installation is not necessary. It is only necessary when openhab is used without internet connection. Otherwise disk space is wasted without any benefit.

**Comment by EvilOlaf** [comment]
Feel free to provide a PR to fix this. Our development efforts are going to its sucessor: https://github.com/armbian/configng

**Comment by igorpecovnik** [comment]
We switch to new one soon, old is unmaintained, will be archived soon.

Adding is simple: https://docs.armbian.com/User-Guide_Armbian-Software/

**Comment by moodyblue** [comment]
Will there be an option in configng to install openhab ?

**Comment by igorpecovnik** [comment]
> Will there be an option in configng to install openhab ?

There are no specific plans. Until end of the year we plan to stabilise what is currently in the system and accepting well tested community contributions.

Try following our instructions. I spent a day making them and they should be on the level that anyone, that knows what GitHub is, should be able to understand them. If not, I will improve them. You should need less then one hour to add OpenHab to this system when doing it first time.

See extension to the build system that generates image with preinstalled OpenHab. This works:
https://github.com/armbian/os/blob/main/userpatches/extensions/openhab.sh

**Comment by igorpecovnik** [comment]
https://docs.armbian.com/User-Guide_Armbian-Software/HomeAutomation/#install-openhab
