### ISSUE TITLE
error install armbian-stretch-desktop

### ISSUE THREAD

**Issue by carlosnewmusic** [armbian/config#23]
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0xb6243420>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0xb6243420>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable

**Comment by igorpecovnik** [comment]
what about if you install it manually, apt install armbian-stretch-desktop ... and where did you try? Please provide all data (armbianmonitor -u) ... if you run Armbian

**Comment by carlosnewmusic** [comment]
![image](https://user-images.githubusercontent.com/19379457/42337377-f4e788d6-8086-11e8-985f-ede3605f9eee.png)
http://ix.io/1g8v

**Comment by igorpecovnik** [comment]
I see you try to install a desktop on top of OMV, which changes system beyond recognition. For their needs. You are running many other services, which could compromise some system files. Hard to say. Our desktop is nothing special - it uses standard XFCE4 desktop + our theming.

I can't reproduce this error. I tried a few different setups. https://pastebin.com/54PMnFY6

**Comment by carlosnewmusic** [comment]
Error when configuring the xorg menu

**Comment by igorpecovnik** [comment]
Absolutely no idea & unrelated to our desktop.
