### ISSUE TITLE
Authentication token manipulation error

### ISSUE THREAD

**Issue by carlosnewmusic** [armbian/config#25]
![1531750795265-1327839880](https://user-images.githubusercontent.com/19379457/42763698-210a6ec0-8914-11e8-8c6c-3a5657aa3753.jpg)

**Comment by igorpecovnik** [comment]
https://forum.armbian.com/forum/31-sd-card-and-power-supply/

**Comment by carlosnewmusic** [comment]
I have formatted the card with sd formatter tool first, I have recorded the image with Etcher and I have the correct feed but still giving the same error

**Comment by igorpecovnik** [comment]
Use forum for technical support. This issue tracker is for build system.
