### ISSUE TITLE
OMV not found

### ISSUE THREAD

**Issue by DevilStyle** [armbian/config#30]
hello, I noticed that since yesterday starting armbian-config in the list of personal software to install, there is no more OMV (openmediavault) why? Thank you

**Comment by igorpecovnik** [comment]
Because its available only for Debian based images. You have to ask OMV folks why they don't support Ubuntu builds.

**Comment by DevilStyle** [comment]
thanks for the answer, absolutely no, until the other day everything worked now no more, thank you

**Comment by igorpecovnik** [comment]
In this case use [forum ](https://forum.armbian.com/forum/2-common-issues/)and provide all possible information.

`armbianmonitor -u`

+ describe what you did.

**Comment by DevilStyle** [comment]
http://ix.io/1l0
this is my monitor... thanks

**Comment by igorpecovnik** [comment]
Your monitor provides no data -> forum.
