### ISSUE TITLE
Install option doesn't set proper filesystem type in boot.cmd

### ISSUE THREAD

**Issue by amateusz** [armbian/config#36]
I wanted to move the whole filesystem to external USB drive. I've used 'install' option in the `armbian-config`. It had asked me to format the new drive, and offered a variety of filesystems (I picked `btrfs`).

Then it had copied the whole filesystem (well, it turns out that without `boot` directory)… so far so good.
It failed to boot; I poked around a bit, and with some [help](https://forum.armbian.com/topic/329-moving-linux-to-sata-or-external-drive/?page=2) I've figured out the boot order and realised, that `setenv` line in `boot.cmd` point to the good drive (UUID), but specifies wrong filesystem type.

> The setup process asks for filesystem type, but forgets to update uboot's `boot.cmd` accordingly
> ```
> setenv bootargs "console=ttyS0,115200 console=tty1 root=UUID=2f938bf2-82d8-4e69-83d9-3c662553dccd rootwait rootfstype=ext4 cgroup_enable=memory
> ```
So I've changed it (lit. `rootfstype=btrfs`), recompiled using `uboot-tools` and voilà.

I'm on ARMBIAN 5.25 stable Debian GNU/Linux 8 (jessie) 4.14.70-sunxi A20 board

**Comment by igorpecovnik** [comment]
> I'm on ARMBIAN 5.25 stable Debian GNU/Linux 8 (jessie) 4.14.70-sunxi A20 board

Thank you, but I guess this problem was fixed with https://github.com/armbian/build/commit/9e018b0ab40965167f0453431a1cdce022417dc6#diff-d9f1078e3fed3bc093787ab0a6240f14
