### ISSUE TITLE
Installing Ubuntu_bionic_next to eMMC on Pine64 LTS erases SD card fs and then can't find binaries

### ISSUE THREAD

**Issue by Anton-Latukha** [armbian/config#44]
If somebody has more info - please add in the comments.

Using Pine64 LTS, flashed Armbian_5.75_Pine64so_Ubuntu_bionic_next_4.19.20 from https://dl.armbian.com/pine64so/Ubuntu_bionic_next.7z on 2019-02-10 to SD card.

1. There is Pine64 LTS with erased eMMC module.
2. Plugged-in SD card and booted the Pine64 LTS.

3. Logged-in through SSH as `root` and ran:
```
apt update
apt upgrade
reboot
```

4. Logging-in again through SSH as `root`:
```
armbian-config
```

5. Choosen menu options: System -> Install to eMMC -> ext4 ->
Further recieving the cycle of:
[loop.txt](https://github.com/armbian/config/files/2869446/loop.txt)

6. After breaking the cycle with Ctrl+C dropped into the shell.
Shell says no binaries.

====

7. Plugging eMMC and SD card to the laptop and inspecting them:
SD card filesystem seems erased. Partition is present. `mount` reports an error :`wrong fs type, bad option, bad superblock on /dev/sdb1, missing codepage or helper program, or other error.` standard error when fs is not present.

**Comment by Anton-Latukha** [comment]
If you need an image of the SD card before it erased itself - I can provide a backup image.

**Comment by igorpecovnik** [comment]
Please move this to the [forum](https://forum.armbian.com/forum/27-allwinner-h5-a64/) and remember to add logs before you start installing to eMMC (armbianmonitor -u). Without that, issue report is invalid and I can only guess that your SD card is failed. I don't have this board nor have possibly to recreate - out of office.
