### ISSUE TITLE
Add bugreporting template/documentation 

### ISSUE THREAD

**Issue by Anton-Latukha** [armbian/config#45]
In #44, - it was expected from me, that I would supply logging information with command `armbianmonitor -u`. It was said that without that, issue report is invalid.
And maybe the same also was meant by confusing `duplicate` tag closing reason in https://github.com/armbian/build/issues/1279, https://github.com/armbian/build/issues/1280, since that are separate issues, I don't know for sure.

During creation of that issues I didn't found bugreporting recommendations in the bugreport template or in README regarding what was appealing to. So I couldn't know that there is a `armbianmonitor -u` command to enable logging and that it should be includded in bugreport.

Please add information to support bugreporting to make them more relevant for you.
There are info in template of `build` repo, and none info for the `config` repo, and info about  `armbianmonitor -u`  is nowhere to be found.

**Comment by igorpecovnik** [comment]
When you login to the system it tells you where support is: forum.armbian.com ... For things that are actually supported you can't open new topic without supplying logs. Without logs your pleads are ignored because that is too expensive for us to cover.
