### ISSUE TITLE
debian-software broken

### ISSUE THREAD

**Issue by ThomasKaiser** [armbian/config#54]
Simple `/bin/bash -n` check:

    ./debian-software: line 1550: syntax error near unexpected token `>'
    ./debian-software: line 1550: `php -q install.php --autoinstall=${TEMP_DIR}/isp.conf.php &>> /var/log/ispconfig_config.log'

**Comment by ThomasKaiser** [comment]
When are you going to push a new armbian-config release to the repo?

**Comment by igorpecovnik** [comment]
https://github.com/armbian/upload/commit/8498de3f97db3e03c15c969c34a80381d35cbf9d

**Comment by igorpecovnik** [comment]
But don't understand why this is wrong way? https://unix.stackexchange.com/questions/159513/what-are-the-shells-control-and-redirection-operators/159514#159514
