### ISSUE TITLE
Can't install OMV

### ISSUE THREAD

**Issue by dushicai** [armbian/config#58]
Device:OrangePi Zero Plus
OS:Debian buster

install log:
--2019-07-12 10:07:45--  https://packages.openmediavault.org/public/archive.key
Resolving packages.openmediavault.org (packages.openmediavault.org)... 178.254.11.33
Connecting to packages.openmediavault.org (packages.openmediavault.org)|178.254.11.33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3134 (3.1K) [application/pgp-keys]
Saving to: '/etc/apt/trusted.gpg.d/openmediavault-archive-keyring.asc'

/etc/apt/trusted.gpg.d/o 100%[==================================>]   3.06K  --.-KB/s    in 0s      

2019-07-12 10:07:46 (35.1 MB/s) - '/etc/apt/trusted.gpg.d/openmediavault-archive-keyring.asc' saved [3134/3134]

OK
Executing: /tmp/apt-key-gpghome.CDYxPElh8K/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 7AA630A1EDEE7D73
gpg: key 7AA630A1EDEE7D73: "OpenMediaVault Plugin Developers <plugins@omv-extras.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
/usr/sbin/softy: line 611: [: 11107: unary operator expected
Now installing OMV packages. Be patient please
(Reading database ... 33848 files and directories currently installed.)
Preparing to unpack .../tmp.BvW7HjPmLw/omv_extras.deb ...
Unpacking openmediavault-omvextrasorg (5.0) over (5.0) ...
/var/lib/dpkg/info/openmediavault-omvextrasorg.postrm: 22: .: Can't open /usr/share/openmediavault/scripts/helper-functions
dpkg: warning: old openmediavault-omvextrasorg package post-removal script subprocess returned error exit status 127
dpkg: trying script from the new package instead ...
/var/lib/dpkg/tmp.ci/postrm: 22: .: Can't open /usr/share/openmediavault/scripts/helper-functions
dpkg: error processing archive /tmp/tmp.BvW7HjPmLw/omv_extras.deb (--install):
 new openmediavault-omvextrasorg package post-removal script subprocess returned error exit status 127
/var/lib/dpkg/tmp.ci/postrm: 22: .: Can't open /usr/share/openmediavault/scripts/helper-functions
dpkg: error while cleaning up:
 new openmediavault-omvextrasorg package post-removal script subprocess returned error exit status 127
Errors were encountered while processing:
 /tmp/tmp.BvW7HjPmLw/omv_extras.deb

**Comment by igorpecovnik** [comment]
Talk to OMV people when they will support Buster. If you want to use OMV, use Stretch.
