### ISSUE TITLE
Ive lost armbian-config. Please, set it has hold by default

### ISSUE THREAD

**Issue by Askmewho** [armbian/config#65]
For some reason, I believe uninstalling some software, my armbian-config its not present on my system anymore. I think thats would never happens, there should be hold by default so no matter what you try to uninstall this key script didnt suffer the same faith.

I am able to reinstall it with this repo? Ive just want to setup everything again ahha

Thanks!

**Comment by igorpecovnik** [comment]
> uninstalling some software,

Possible, dependencies are not perfectly set. Just run:

`apt install armbian-config`
