### ISSUE TITLE
about gpu scaling

### ISSUE THREAD

**Issue by Askmewho** [armbian/config#66]
Hi! 
I have some questions about gpu scaling. they are present on my rockpi4 dtb some scaling options
for the gpu itself. but they are on hexadecimal values and its a bit messy going around dtbs, unpacking , packing, etc.

1) there is any way to know the actual freq of the gpu from terminal?
just to know if the OC works when I edit the dtb.
2) it would be a great feature having this scaling from the armbian-config. but as another dev told me it should be done for each particular board... but being based on the dtb it should not be that way.. just a thought. if the options are on the dtb there must be a way to select from them.
3) Coming from rpi sbcs I am amazed how easy you can scale your cpu from these config file, without even reboot like on rpi. it should be related to not having thread x os on top of linux. 

off topic from last issue: when ive tried to reinstall the armbian-config I didnt do update before, thas why ive never found it before and sent that nonsense issue hahahhaha so stupid from me. 

thanks on advance. wonderful os.

**Comment by igorpecovnik** [comment]
https://forum.armbian.com/forum/33-rockchip-3399/
