### ISSUE TITLE
Strange GUI

### ISSUE THREAD

**Issue by jotoeri** [armbian/config#68]
Hi all,
i just updated my BananaPi to Armbian Buster (Armbian 5.91).
The configuration utility there seems to be broken in its 'Graphics' (see picture). The submenus look alike, even that special submodules as the Timezone-Module still look good.
Unfortunately i don't know, where this could come from, so i can't fix it by myself. :/
Greets,
Jonas

![armbian-config](https://user-images.githubusercontent.com/47433654/64424738-22e59600-d0aa-11e9-95b2-65872f4ef9cd.PNG)

**Comment by jotoeri** [comment]
Ahhh....! I just forgot: By moving the cursor it gets even worse... ;)
![armbian-config2](https://user-images.githubusercontent.com/47433654/64424955-c33bba80-d0aa-11e9-97d2-31932d03f5d8.PNG)

**Comment by igorpecovnik** [comment]
> The configuration utility there seems to be broken

Known bug. Not ours - some core component or terminal handling. But if solution is found, we will adopt a workaround.

https://packages.debian.org/buster/dialog
https://packages.debian.org/buster/libncursesw6

**Comment by jotoeri** [comment]
Ok, nice. Thank you. ;)
