### ISSUE TITLE
Switch to non-English locale and add support for Cyrillic characters. 

### ISSUE THREAD

**Issue by Borisvit** [armbian/config#69]
Adding and switching locales using standard methods via "dpkg-reconfigure locales" and "dpkg-reconfigure console-setup" are not used on the system. Cyrillic characters are not displayed. 

The solution is to edit the file "/etc/environment" in which you need to replace LC_ALL = "C" with LC_ALL = "your locale" (in my case, uk_UA.utf8). After that, there were no problems with displaying cryrilic symbols.

It may be possible to add the locale in the "/etc/environment" file to the script after selecting the default locale.

Tested on Ubuntu Bionic with Armbian Linux 4.19.63-sunxi64 for NanoPi Neo2.

Sorry for my English. (Google translate)

**Comment by igorpecovnik** [comment]
https://github.com/armbian/build/pull/1617
