### ISSUE TITLE
Installing OS from SD to eMMC missing in Buster

### ISSUE THREAD

**Issue by easyyu** [armbian/config#70]
I coudn't find in menu System -> Install optin for cloning OS from SD to eMMC.
How can I get it back as on older version?
Boards are Orange Pi +2E and Orange Pi PC+
OS Armbian v5.91
I tied even:
`git clone https://github.com/armbian/config
cd config
bash debian-config`
but same...
Thx

**Comment by igorpecovnik** [comment]
Technical support = https://forum.armbian.com/
