### ISSUE TITLE
Integrated External RTC Module configuration

### ISSUE THREAD

**Issue by septs** [armbian/config#79]
I think `armbian-config` can provide a convenient configuration External RTC module

I don't know how to configure the I2C-RTC module so that it is automatically used during kernel initialization

e.q: DS3231 for Pi module ([product link](https://www.pishop.us/product/ds3231-real-time-clock-module-for-raspberry-pi/))

**Comment by igorpecovnik** [comment]
Its slightly different depending on the hardware family but basically you need to enable I2C (which is mainly enabled/disabled in armbian-config -> system -> hardware) ... the rest is the same.
