### ISSUE TITLE
After installing OMV5 on the Phicomm N1 box Armbian20.02.05, the system cannot be accessed after restarting, and it hangs on the LOGO interface.

### ISSUE THREAD

**Issue by molun** [armbian/config#85]
Restart the system card logo, the system will not get the IP without entering the system

**Comment by igorpecovnik** [comment]
https://github.com/armbian/config/issues/76

**Comment by igorpecovnik** [comment]
If you have boot/hardware related troubles try asking in [this sub-forum](https://forum.armbian.com/forum/24-tv-boxes/). This hardware is officially **not supported** by Armbian. [Those are](https://www.armbian.com/download/?device_support=Supported).
