### ISSUE TITLE
Source install fails

### ISSUE THREAD

**Issue by Averell7** [armbian/config#88]
armbian-config used on a Asus Tinkerboard. 
Menu software / source_install. 
When the work is finished, in the /usr/src/linux-source-5.4.28-rochchip directory, there is a single file, .config, nothing else. 
software / header_install work properly
The linux-source...._all.deb file is correctly downloaded, I could get it from /var/cache/apt/archives.

The script indicates that it is uncompressing, configuring, and there is no error message. May be a simple error in the command which (I guess) would delete the tar files, and which deletes everything ?

**Comment by igorpecovnik** [comment]
Test resoults shows sorces has been succesfully installed. Are you using updated images from the download section or your own builds?

https://dl.armbian.com/_test-reports/2020-03-31_01.03.57.html

> May be a simple error in the command which (I guess) would delete the tar files, and which deletes everything ?

https://github.com/armbian/config/blob/master/debian-config-jobs#L187-L229

**Comment by igorpecovnik** [comment]
Tested now manually - it works as expected. Closing.

Feel free to open if it doesn't work on a clean build.

**Comment by Averell7** [comment]
I just installed armbian-config today, after an apt update. The Tinker board linux is downloaded from your website : Armbian Buster with Linux 5.4.14-rockchip
I verified :
The source is correctly downloaded. 
The two .xz files are correctly installed in /usr/src
I have not yet been able to see if at some stage the package is really extracted. 
In the end, only the .config file remains.

**Comment by igorpecovnik** [comment]
Did you reboot after updating?

**Comment by Averell7** [comment]
Yes, I rebooted. But I found the trick (not tested yet but quite sure this is the reason). pv was not present on my system. So please, add it to armbian-config dependencies.

**Comment by Averell7** [comment]
OK, it works now.
