### ISSUE TITLE
uninstalling software

### ISSUE THREAD

**Issue by sjude68** [armbian/config#97]
how to uninstall sw which is installed by armbian-config

**Comment by EvilOlaf** [comment]
This feature is not implemented and noone is working on it. If you like to add it feel free to contribute: 
https://github.com/armbian/build#contribute

**Comment by sjude68** [comment]
I could uninstall plex server manually using
aptget remove plexmediaserver
This gave me some space. My 8gb sd card was full so couldn't do any aptget upgrade
